### PR TITLE
Update setup.sh

### PR DESCRIPTION
**Pull request by ShawnKupfer**
Update region to westus2 per AB#795011

### CODE REVIEW

**Comment by zr-msft** [comment]
LGTM

**Comment by ShawnKupfer** [comment]
@ckittel Are you able to merge this PR?

**Comment by ckittel** [comment]
I cannot, I don't have permissions on this repo.

**Comment by ckittel** [comment]
@cryophobia -- looks like you're owner in our OpenSource Management Portal.  Maybe you can help out above.

**Pull request merged**
